# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Antonio Álvarez Feijoo"
description: > # this means to ignore newlines until "email:"
   Software Engineer

email: aafeijoo@gmail.com
#blog logo
logo: "/assets/images/aafeijoo_avatar.jpg"
logo_small: "/assets/images/aafeijoo_avatar_small.png"
# blog cover
cover: "/assets/images/articles/2014-05-12-principles-of-flight-simulation/principles_of_flight_simulation.jpg"

name: 'Antonio Álvarez Feijoo'
author: 'Antonio Álvarez Feijoo'
author_image: "/assets/images/aafeijoo_avatar.jpg"

paginate:	6

url: "http://aafeijoo.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/aafeijoo
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
