# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Antonio Álvarez Feijoo"
description: > # this means to ignore newlines until "email:"
   Software Engineer

email: aafeijoo@gmail.com
#blog logo
logo: "/assets/images/aafeijoo_avatar.jpg"
logo_small: "/assets/images/aafeijoo_avatar_small.png"
# blog cover
cover: "/assets/images/articles/2014-05-12-principles-of-flight-simulation/principles_of_flight_simulation.jpg"

name: 'Antonio Álvarez Feijoo'
author: 'Antonio Álvarez Feijoo'
author_image: "/assets/images/aafeijoo_avatar.jpg"

paginate:	10

url: "http://aafeijoo.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	linkedin-square
    url:	https://www.linkedin.com/in/aafeijoo
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/aafeijoo
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
